## 1. Activate your facefusion:
Run this command: ```conda activate facefusion```

After running the command, it display the message: ```CondaError: Run 'conda init' before 'conda activate```


## 2. Solution â€” Source the shell configuration
Run the following command to reload your shell configuration (for mac): ```source ~/.zshrc```

Try activating the environment again: ```conda activate facefusion```

The status changed: ```(facefusion) username@```
